name: Prepare Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          make_latest: true
